spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.2.50:8848
        group: SDX_A_GROUP
      config:
        server-addr: 10.0.8.50:8848
        group: SDX_A_GROUP
  redis:
    host: 10.0.8.1
    port: 6379
    password: 1653500059bd453d93253f7f7c088ff7
    database: 0
    timeout: 3000
    cache:
      expiration: 3600
      expries: '{"application":1800, "test1":0, "test2":1800}'
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8

# 网关验签依赖日志打印
gateway:
  log:
    enable: true
    ignoreUrls:
      - /api/uaa/common/upload
  sign:
    enable: true
    key:
      'sdx-manage-uaa': 'OpLyfckC0F8KVml6'
    ignoreUrls:
      - /api/uaa/common/upload
    timeout: 600000
  auth:
    enable: true
    secret: 7NzrNPzVQ24ZtypWjD24rV9wpOHO1Lxg
    ignoreUrls:
      - /api/uaa/common/upload
      - /api/uaa/common/wechat/upload
      - /api/uaa/common/systemTime

logging:
  level:
    root: INFO
    com.xy.nebulaol: DEBUG
  logback:
    path: /home/sdx/logs
    name: ${spring.application.name}
